[project]
name = "pythonpart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "LTLeonid", email = "contact@ltleonid.ru" }
]
requires-python = ">=3.14"
dependencies = [
    "grpcio>=1.83.0",
    "grpcio-tools>=1.83.0",
]

[project.scripts]
pythonpart = "pythonpart:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
