# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: process.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'process.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rprocess.proto\"8\n\x07Request\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06lenght\x18\x02 \x01(\x03\x12\x0f\n\x07provide\x18\x03 \x03(\t\"N\n\x08Response\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06lenght\x18\x02 \x01(\x03\x12\x0f\n\x07provide\x18\x03 \x03(\t\x12\x13\n\x0b\x63ount_words\x18\x04 \x01(\x03\x32\x31\n\x0e\x43SharpToPython\x12\x1f\n\x08GetCount\x12\x08.Request\x1a\t.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'process_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=17
  _globals['_REQUEST']._serialized_end=73
  _globals['_RESPONSE']._serialized_start=75
  _globals['_RESPONSE']._serialized_end=153
  _globals['_CSHARPTOPYTHON']._serialized_start=155
  _globals['_CSHARPTOPYTHON']._serialized_end=204
# @@protoc_insertion_point(module_scope)
